### ISSUE TITLE
Expose Concourse metatdata to tags

### ISSUE THREAD

**Issue by duelyy** [concourse/datadog-event-resource#17]
### Is your feature request related to a problem? Please describe.

It would be great if we can expose the Concourse metadata e.g. $BUILD_ID, $BUILD_NAME, etc to tags

### Describe the solution you'd like

When building the Concourse pipeline yml file, any variables under the `tag` section will not interpolate

```
- put: datadog-event
  params:
    title: Did you hear the news today?
    text: Oh boy!
    priority: normal
    tags:
    - environment:test
    - build-id:$BUILD_ID
    alert_type: info
```
